### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by taynotfound** [Prozilla/Prozilla-OS#1]
- File Explorer
- Window Resize
- Way to Update Window Name

**Comment by Prozilla** [comment]
Window resize is now done: 42b0883997f9dba44551021554f038c3a5dd4594

**Comment by Prozilla** [comment]
File explorer: 716f21d3fb9d1b752af2904f7db7d1bbd4d18ad2
Dynamic window titles: 5f201a35ec5fdd6d0e93d383bfcabd6db35c3a98
